//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyVersion("1.0.0")]
[assembly: AssemblyFileVersion("1.0.0.53606")]
[assembly: AssemblyInformationalVersion("1.0.0")]
[assembly: AssemblyTitle("Cogworks.ExamineInspector")]
[assembly: AssemblyDescription("This project is effectively a web based cut down LUKE. It allows you to query your examine indexes in the umbraco backoffice.")]
[assembly: AssemblyCompany("Cogworks")]
[assembly: AssemblyProduct("Cogworks.ExamineInspector")]
[assembly: AssemblyCopyright("Copyright © 2017")]

