//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;
using Cogworks.ExamineInspector.Helpers;

[assembly: AssemblyVersion(GlobalAssemblyInfo.SimpleVersion)]
[assembly: AssemblyFileVersion(GlobalAssemblyInfo.SimpleVersion)]
[assembly: AssemblyInformationalVersion(GlobalAssemblyInfo.InformationalVersion)]

//// AssemblyVersion = full version info, since it's used to determine agents versions
//[assembly: AssemblyVersion(Xamarin.ThisAssembly.Version)]
//// FileVersion = release-like simple version (i.e. 3.11.2 for cycle 5, SR2).
//[assembly: AssemblyFileVersion(Xamarin.ThisAssembly.SimpleVersion)]
//// InformationalVersion = full version + branch + commit sha.
//[assembly: AssemblyInformationalVersion(Xamarin.ThisAssembly.InformationalVersion)]

[assembly: AssemblyTitle("Cogworks.ExamineInspector")]
[assembly: AssemblyDescription("This project is effectively a web based cut down LUKE. It allows you to query your examine indexes in the umbraco backoffice.")]
[assembly: AssemblyCompany("Cogworks")]
[assembly: AssemblyProduct("Cogworks.ExamineInspector")]
[assembly: AssemblyCopyright("Copyright © 2017")]